### ISSUE TITLE
swift-syntax upper bound (<603.0.0) makes the package unbuildable on Xcode 26.6 / Swift 6.3

### ISSUE THREAD

**Issue by mc1100** [eu-digital-identity-wallet/SwiftCopyableMacro#15]
## Summary

`SwiftCopyableMacro` cannot be built with Xcode 26.6 / Swift 6.3, because its `swift-syntax`
dependency is capped below the `603.x` generation that a Swift 6.3 toolchain needs:

https://github.com/eu-digital-identity-wallet/SwiftCopyableMacro/blob/ba0d1318b825b69d8c0bd5ae65746300c95aa972/Package.swift#L18

```swift
.package(url: "https://github.com/swiftlang/swift-syntax.git", "600.1.0"..<"603.0.0")
```

SPM therefore resolves `swift-syntax 602.0.0`, and the macro plugin fails to compile against the
6.3 compiler-plugin interface.

I can see from #14 that the closed upper bound was added deliberately — it replaced an open-ended
`from: "509.0.0"` — so this is a request to raise the ceiling for the current toolchain rather than a
report of an oversight.

## Environment

| | |
|---|---|
| Xcode | 26.6 (17F113) |
| Swift | 6.3.3 (`swiftlang-6.3.3.1.3`, `clang-2100.1.1.101`) |
| `SwiftCopyableMacro` | 0.0.5 (the latest tag, and equal to `main`) |
| resolved `swift-syntax` | 602.0.0 |

## What happens

A command-line build first stops at Xcode's macro-trust gate:

```
SwiftCopyableMacro/Package.swift:PACKAGE-TARGET:CopyablePlugin: error:
  Macro "CopyablePlugin" from package "Copyable" must be enabled before it can be used
```

(That part is Xcode's own prompt, not this package's doing — `-skipMacroValidation` gets past it.)
Then the real failure:

```
Sources/CopyablePlugin/CopyablePlugin.swift:16:8: error:
  unable to resolve module dependency: 'SwiftCompilerPlugin'
Sources/CopyablePlugin/CopyablePlugin.swift:17:8: error:
  unable to resolve module dependency: 'SwiftSyntaxMacros'
Sources/CopyablePlugin/Diagnostic/CopyableDiagnostic.swift:16:8: error:
  unable to resolve module dependency: 'SwiftSyntax'
Sources/CopyablePlugin/Diagnostic/CopyableDiagnostic.swift:17:8: error:
  unable to resolve module dependency: 'SwiftDiagnostics'
```

## Why

`swift-syntax` releases track the Swift release they belong to — `600.x` → Swift 6.0, `601.x` → 6.1,
`602.x` → 6.2, `603.x` → 6.3. The `603` line has been stable for months:
`603.0.0` (2026-03-24), `603.0.1` (2026-04-21), `603.0.2` (2026-06-08).

`..<"603.0.0"` excludes all of them, so on a Swift 6.3 toolchain SPM can only pick `602.0.0`, whose
macro-plugin modules do not match the compiler the plugin is being built with.

## Suggested fix

Raise the upper bound one generation:

```swift
.package(url: "https://github.com/swiftlang/swift-syntax.git", "600.1.0"..<"604.0.0")
```

and cut a tag, since `0.0.5` is what SPM resolves. Worth compiling against `603.0.2` first rather than
just widening the range — the point of the bound in #14 was presumably to keep `swift-syntax` API churn
out, and 603 may need small adjustments.

## How we hit it

Transitively, adding the wallet's own RQES UI library to an app:

```
eudi-lib-ios-rqes-ui 0.4.3
  └─ SwiftCopyableMacro (from: 0.0.5)
       └─ swift-syntax  "600.1.0"..<"603.0.0"   ← resolves 602.0.0, cannot build on Swift 6.3
```

Everything else in that graph resolves and builds on Xcode 26.6, including `eudi-lib-podofo`'s
xcframework — this is the only thing that stops it. So in practice
`eu-digital-identity-wallet/eudi-lib-ios-rqes-ui` cannot currently be integrated on a current Xcode,
which is how a downstream integrator meets this.

## Reproduction

```
xcodebuild -project <app>.xcodeproj -scheme <app> -sdk iphonesimulator \
  -destination 'platform=iOS Simulator,name=iPhone 17' \
  -skipMacroValidation build
```
with `eudi-lib-ios-rqes-ui` 0.4.3 (or `SwiftCopyableMacro` 0.0.5 directly) as a package dependency, on
Xcode 26.6.
